apiVersion: v1
kind: Secret
metadata:
  name: cloud-secrets
  namespace: cloud-auction
type: Opaque
stringData:
  DATABASE_URL: host=postgres port=5432 user=postgres dbname=cloud sslmode=disable
  JWT_SECRET: replace-me
  INTERNAL_SERVICE_TOKEN: replace-me
